import "./globals.css";
import { Outfit } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import Provider from "./provider";
import DashboardLayoutWrapper from "./dashboard/_components/DashboardLayoutWrapper";
import { Toaster } from "sonner";
import { CourseProvider } from "../context/CourseContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const outfit = Outfit({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={outfit.className} suppressHydrationWarning>
          <Provider>
            <CourseProvider>
            <DashboardLayoutWrapper>
              {children}
            </DashboardLayoutWrapper>
            </CourseProvider>
          </Provider>
          <Toaster richColors position="top-right" />
        </body>
      </html>
    </ClerkProvider>
  );
}
